app:
  storage:
    path: ${APP_STORAGE_PATH:./uploads}

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/secret_santa}
    username: ${DB_USERNAME:secret_santa_user}
    password: ${DB_PASSWORD:secret}

  flyway:
    enabled: true

  jpa:
    hibernate:
      ddl-auto: validate

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 6MB
