app:
  storage:
    path: ${APP_STORAGE_PATH:./uploads}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/secret_santa
    username: secret_santa_user
    password: secret

  flyway:
    enabled: true

  jpa:
    hibernate:
      ddl-auto: validate

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 6MB
